%% Import data from spreadsheet
% Script for importing data from the following spreadsheet:
%
%    Workbook: D:\University of Toronto\Xiaolin Wei - Covid modeling study\COV_19_Data_revised\Canada\Canada_COVID19.xlsx
%    Worksheet: Sheet1
%
% Auto-generated by MATLAB on 13-May-2020 22:18:24

%% Setup the Import Options and import the data
opts = spreadsheetImportOptions("NumVariables", 19);

% Specify sheet and range
opts.Sheet = "Sheet1";
opts.DataRange = "A4:S85";

% Specify column names and types
opts.VariableNames = ["Var1", "Var2", "Var3", "Var4", "cum_confirm_symptomatic", "Var6", "Var7", "Var8", "Var9", "Var10", "Var11", "d_Hospitalised", "Var13", "Var14", "Var15", "Var16", "Var17", "Var18", "daily_testing"];
opts.SelectedVariableNames = ["cum_confirm_symptomatic", "d_Hospitalised", "daily_testing"];
opts.VariableTypes = ["char", "char", "char", "char", "double", "char", "char", "char", "char", "char", "char", "double", "char", "char", "char", "char", "char", "char", "double"];

% Specify variable properties
opts = setvaropts(opts, ["Var1", "Var2", "Var3", "Var4", "Var6", "Var7", "Var8", "Var9", "Var10", "Var11", "Var13", "Var14", "Var15", "Var16", "Var17", "Var18"], "WhitespaceRule", "preserve");
opts = setvaropts(opts, ["Var1", "Var2", "Var3", "Var4", "Var6", "Var7", "Var8", "Var9", "Var10", "Var11", "Var13", "Var14", "Var15", "Var16", "Var17", "Var18"], "EmptyFieldRule", "auto");

% Import the data
tbl = readtable("D:\University of Toronto\Xiaolin Wei - Covid modeling study\COV_19_Data_revised\Canada\Canada_COVID19.xlsx", opts, "UseExcel", false);

%% Convert to output type
exp_C = tbl.cum_confirm_symptomatic.';
d_Hospitalised = tbl.d_Hospitalised.';
daily_testing = tbl.daily_testing.';

%% Clear temporary variables
clear opts tbl