%% Import data from spreadsheet
% Script for importing data from the following spreadsheet:
%
%    Workbook: D:\University of Toronto\Xiaolin Wei - Covid modeling study\COV_19_Data_revised\Hubei_COVID19.xlsx
%    Worksheet: Sheet1
%
% Auto-generated by MATLAB on 07-May-2020 15:23:00

%% Setup the Import Options and import the data
opts = spreadsheetImportOptions('NumVariables', 18);

% Specify sheet and range
opts.Sheet = 'Sheet1';
opts.DataRange = 'A2:R140';

% Specify column names and types
opts.VariableNames = ['Var1', 'Var2', 'Var3', 'Var4', 'cum_confirm_symptomatic', 'Var6', 'Var7', 'Var8', 'Var9', 'c_Quarantine', 'Var11', 'd_Hospitalised', 'Var13', 'Var14', 'Var15', 'Var16', 'Var17', 'active_infection'];
opts.SelectedVariableNames = ['cum_confirm_symptomatic', 'c_Quarantine', 'd_Hospitalised', 'active_infection'];
opts.VariableTypes = ['char', 'char', 'char', 'char', 'double', 'char', 'char', 'char', 'char', 'double', 'char', 'double', 'char', 'char', 'char', 'char', 'char', 'double'];

% Specify variable properties
opts = setvaropts(opts, ['Var1', 'Var2', 'Var3', 'Var4', 'Var6', 'Var7', 'Var8', 'Var9', 'Var11', 'Var13', 'Var14', 'Var15', 'Var16', 'Var17'], 'WhitespaceRule', 'preserve');
opts = setvaropts(opts, ['Var1', 'Var2', 'Var3', 'Var4', 'Var6', 'Var7', 'Var8', 'Var9', 'Var11', 'Var13', 'Var14', 'Var15', 'Var16', 'Var17'], 'EmptyFieldRule', 'auto');

% Import the data
tbl = readtable('C:\Users\David\Documents\GitHub\Covid19\Jianhuig\Hubei_COVID19.xlsx', opts, 'UseExcel', false);

%% Convert to output type
exp_C = tbl.cum_confirm_symptomatic.';
c_Quarantine = tbl.c_Quarantine.';
d_Hospitalised = tbl.d_Hospitalised.';
d_infection = tbl.active_infection.';

%% Clear temporary variables
clear opts tbl